// src/components/01-atoms/Button.tsx
import type { ReactNode } from "react";

export default ({ url, small, inverse, onclick, children, classes }: {url?: string, onclick?: any, children: string|ReactNode, small?: boolean, inverse?: boolean, classes?: string|string[] }) => {
  const Element = url ? 'a' : 'button';

  const attributes: {[key: string]: string|string[]} = {
    className: [
      'border-1',
      small ? 'p-1' : 'p-1.25',
      small ? 'pt-0.5' : 'pt-0.75',
      small ? 'pb-0.5' : 'pb-0.75',
      small ? 'text-[16px]' : 'text-base',
      'rounded-md',
      'font-bold',
      'hover:border-current',
      'focus:border-current',
    ],
    onClick: onclick,
  }

  if (inverse) {
    attributes.className?.push(
      'text-secondary-1',
      'border-current',
      'hover:bg-secondary-1',
      'focus:bg-secondary-1',
      'hover:border-secondary-1',
      'focus:border-secondary-1',
      'hover:text-nearblack',
      'focus:text-nearblack',
    );
  } else {
    attributes.className?.push(
      'bg-primary-5',
      'text-white',
      'border-transparent',
      'hover:bg-primary',
      'focus:bg-primary',
    );
  }

  if (classes) attributes.className.push(classes);

  attributes.className = attributes.className.join(' ');


  if (url) attributes.href = url;

  return (
    <Element {...attributes}>{children}</Element>
  );
}

// src/components/01-atoms/Button/Button.svelte
<script>
  const { type, modifier, href, classes, children } = $props();

  const attributes = {
    type,
    href,
    class: [
      'font-bold',
      'pt-[8px]',
      'pb-[8px]',
      'pl-1',
      'pr-1',
      'mt-1',
      'mb-1',
    ],
  };

  if (modifier === 'secondary') {
    attributes.class.push('text-charcoal', 'bg-secondary-1', 'hover:bg-offwhite');
  } else {
    attributes.class.push('text-primary-5', 'bg-primary-1', 'hover:bg-primary-4', 'hover:text-neutral-1');
  }

  if (classes?.length) attributes.class.push(...classes);
</script>

{#if href}
  <a {...attributes}>{@render children()}</a>
{:else}
  <button {...attributes}>{@render children()}</button>
{/if}
